import type {
  MarketResearchSource,
  MarketSourceCategory,
  MarketSourceFilters,
} from './market-research-source-types';
import {
  MARKET_SOURCE_ACCESS,
  MARKET_SOURCE_AUTH,
  MARKET_SOURCE_CADENCES,
  MARKET_SOURCE_CATEGORIES,
  MARKET_SOURCE_COVERAGE,
  MARKET_SOURCE_OUTPUTS,
  MARKET_SOURCE_STATUSES,
} from './market-research-source-types';

const PROVIDER_POINT_CAVEAT = 'Map point represents source/provider location, not observation geography.';

const scores = (
  sourceAuthority: number,
  domainFit: number,
  gisReadiness: number,
  freshness: number,
  apiReadiness: number,
  licenseSafety: number,
  integrationPriority: number,
) => ({
  sourceAuthority,
  domainFit,
  gisReadiness,
  freshness,
  apiReadiness,
  licenseSafety,
  integrationPriority,
});

export const marketSourceCategoryLabels: Record<MarketSourceCategory, string> = {
  backbone: 'GIS Backbone',
  cpg_retail: 'CPG / Retail',
  pharma_health: 'Pharma / Health',
  finance_macro: 'Finance / Macro',
  policy_regulation: 'Policy / Regulation',
  live_risk: 'Live Risk',
};

export const marketSourceCategoryColors: Record<MarketSourceCategory, string> = {
  backbone: '#00E5FF',
  cpg_retail: '#D4AF37',
  pharma_health: '#00E676',
  finance_macro: '#448AFF',
  policy_regulation: '#FF9500',
  live_risk: '#FF3D3D',
};

export const marketResearchSources = [
  {
    id: 'ipums-nhgis',
    name: 'IPUMS NHGIS',
    provider: 'IPUMS',
    category: 'backbone',
    summary: 'Historical Census, ACS, time-series tables, GIS boundary files, and geographic crosswalks.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://api.ipums.org/',
    docsUrl: 'https://developer.ipums.org/docs/v2/apiprogram/apis/nhgis/',
    auth: 'free_key',
    access: 'open',
    cadence: 'release_calendar',
    spatialResolution: 'Nation, state, county, tract, block group, and historical geographies.',
    joinKeys: ['GEOID', 'GISJOIN', 'year'],
    licenseNotes: 'Free registration and citation required.',
    caveats: ['Not live. Best used for historical and benchmark layers.', PROVIDER_POINT_CAVEAT],
    location: { label: 'IPUMS, University of Minnesota', lat: 44.974, lng: -93.2277 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(5, 5, 5, 1, 4, 4, 5),
  },
  {
    id: 'us-census-data-api',
    name: 'U.S. Census Data API',
    provider: 'U.S. Census Bureau',
    category: 'backbone',
    summary: 'ACS, Decennial, economic, population, and geography query endpoints for market baselines.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://api.census.gov/data.html',
    docsUrl: 'https://www.census.gov/data/developers/guidance/api-user-guide.html',
    auth: 'free_key',
    access: 'open',
    cadence: 'release_calendar',
    spatialResolution: 'Nation through block group depending on dataset.',
    joinKeys: ['GEOID', 'state', 'county', 'tract', 'NAICS'],
    licenseNotes: 'Public domain U.S. government data.',
    caveats: ['API key is recommended or required for reliable production access.', PROVIDER_POINT_CAVEAT],
    location: { label: 'U.S. Census Bureau, Suitland', lat: 38.8462, lng: -76.9274 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(5, 5, 5, 2, 5, 5, 5),
  },
  {
    id: 'census-tigerweb',
    name: 'TIGERweb REST Services',
    provider: 'U.S. Census Bureau',
    category: 'backbone',
    summary: 'REST GIS boundary services for Census geographies and map-ready boundary joins.',
    coverage: 'us',
    gisMode: 'coordinates',
    output: 'polygons',
    endpointUrl: 'https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/',
    docsUrl: 'https://tigerweb.geo.census.gov/tigerwebmain/TIGERweb_main.html',
    auth: 'none',
    access: 'open',
    cadence: 'annual',
    spatialResolution: 'Census polygons from national to block-level services.',
    joinKeys: ['GEOID', 'STATEFP', 'COUNTYFP', 'TRACTCE'],
    licenseNotes: 'Public domain U.S. government data.',
    caveats: ['Use as a geometry source, not a market metric source.', PROVIDER_POINT_CAVEAT],
    location: { label: 'U.S. Census Bureau, Suitland', lat: 38.8462, lng: -76.9274 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(5, 4, 5, 2, 5, 5, 5),
  },
  {
    id: 'openstreetmap-overpass',
    name: 'OpenStreetMap Overpass API',
    provider: 'OpenStreetMap community',
    category: 'backbone',
    summary: 'POIs, amenities, roads, land use, buildings, retail adjacency, and transport context.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'poi_points',
    endpointUrl: 'https://overpass-api.de/api/interpreter',
    docsUrl: 'https://wiki.openstreetmap.org/wiki/Overpass_API',
    auth: 'none',
    access: 'open',
    cadence: 'minutes',
    spatialResolution: 'Node, way, and relation geometries.',
    joinKeys: ['osm_id', 'tags', 'name'],
    licenseNotes: 'Open Database License; attribution and share-alike obligations apply.',
    caveats: ['Community coverage varies by market.', 'Use rate limits conservatively.', PROVIDER_POINT_CAVEAT],
    location: { label: 'OpenStreetMap Foundation, Cambridge', lat: 52.2053, lng: 0.1218 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(4, 5, 5, 4, 4, 3, 5),
  },
  {
    id: 'overture-maps',
    name: 'Overture Maps',
    provider: 'Overture Maps Foundation',
    category: 'backbone',
    summary: 'Open global places, buildings, addresses, transportation, and administrative divisions.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'poi_points',
    endpointUrl: 'https://docs.overturemaps.org/',
    docsUrl: 'https://docs.overturemaps.org/',
    auth: 'none',
    access: 'open',
    cadence: 'monthly',
    spatialResolution: 'Global GeoParquet themes with stable IDs.',
    joinKeys: ['id', 'theme', 'type', 'confidence'],
    licenseNotes: 'Open data licenses vary by theme; check attribution terms.',
    caveats: ['Distributed as files, not a low-latency query API.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Overture Maps Foundation', lat: 37.4443, lng: -122.1598 },
    bbox: [-180, -85, 180, 85],
    status: 'candidate',
    scores: scores(4, 5, 5, 2, 3, 4, 4),
  },
  {
    id: 'datagov-catalog',
    name: 'Data.gov CKAN Catalog',
    provider: 'U.S. General Services Administration',
    category: 'backbone',
    summary: 'Discovery API for federal, state, local, and tribal open datasets.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'enrichment_table',
    endpointUrl: 'https://catalog.data.gov/api/3/action/package_search',
    docsUrl: 'https://open.gsa.gov/api/datadotgov/',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Dataset metadata, often with publisher-provided spatial extents.',
    joinKeys: ['identifier', 'publisher', 'tags'],
    licenseNotes: 'Metadata is open; downstream dataset licenses vary.',
    caveats: ['Catalog metadata does not guarantee usable API endpoints.', PROVIDER_POINT_CAVEAT],
    location: { label: 'GSA, Washington DC', lat: 38.8836, lng: -77.0199 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(5, 4, 3, 3, 4, 4, 4),
  },
  {
    id: 'socrata-soda',
    name: 'Socrata SODA APIs',
    provider: 'Tyler Technologies Socrata portals',
    category: 'backbone',
    summary: 'City, county, and state APIs for permits, 311, inspections, licenses, parcels, and public health.',
    coverage: 'state_local',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://dev.socrata.com/docs/endpoints',
    docsUrl: 'https://dev.socrata.com/docs/queries/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Dataset-specific points, polygons, addresses, and tabular joins.',
    joinKeys: ['dataset_id', 'location', 'permit_id', 'business_license'],
    licenseNotes: 'Portal-specific; many local datasets are open with attribution.',
    caveats: ['Schemas differ across portals.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Socrata, Seattle', lat: 47.6062, lng: -122.3321 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(4, 5, 4, 4, 5, 4, 5),
  },
  {
    id: 'arcgis-rest-feature-services',
    name: 'ArcGIS REST Feature Services',
    provider: 'Esri and public-sector publishers',
    category: 'backbone',
    summary: 'Common GIS API surface for parcels, zoning, hazards, facilities, traffic, and public infrastructure.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'polygons',
    endpointUrl: 'https://services.arcgis.com/',
    docsUrl: 'https://developers.arcgis.com/rest/services-reference/enterprise/query-feature-service-layer/',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Feature service points, lines, polygons, and metadata.',
    joinKeys: ['OBJECTID', 'GlobalID', 'geometry'],
    licenseNotes: 'Publisher-specific terms; do not assume redistribution rights.',
    caveats: ['Endpoint stability and rate limits vary by agency.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Esri, Redlands', lat: 34.0556, lng: -117.1825 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(4, 5, 5, 4, 5, 3, 5),
  },
  {
    id: 'census-geocoder',
    name: 'Census Geocoder',
    provider: 'U.S. Census Bureau',
    category: 'backbone',
    summary: 'Address and coordinate geocoding with Census geography lookups for market joins.',
    coverage: 'us',
    gisMode: 'coordinates',
    output: 'enrichment_table',
    endpointUrl: 'https://geocoding.geo.census.gov/geocoder/',
    docsUrl: 'https://www.census.gov/programs-surveys/geography/technical-documentation/complete-technical-documentation/census-geocoder.html',
    auth: 'none',
    access: 'open',
    cadence: 'annual',
    spatialResolution: 'Address, coordinate, tract, block, county, and state lookup.',
    joinKeys: ['GEOID', 'matchedAddress', 'coordinates'],
    licenseNotes: 'Public domain U.S. government service.',
    caveats: ['Batch and interactive service limits apply.', PROVIDER_POINT_CAVEAT],
    location: { label: 'U.S. Census Bureau, Suitland', lat: 38.8462, lng: -76.9274 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(5, 4, 5, 2, 4, 5, 4),
  },
  {
    id: 'foursquare-places',
    name: 'Foursquare Places API',
    provider: 'Foursquare',
    category: 'cpg_retail',
    summary: 'Place search, categories, geotagging, venue metadata, and local discovery.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'poi_points',
    endpointUrl: 'https://api.foursquare.com/v3/places/search',
    docsUrl: 'https://docs.foursquare.com/developer/docs/places-api-overview',
    auth: 'account_key',
    access: 'freemium',
    cadence: 'minutes',
    spatialResolution: 'Venue point, address, category, chain, and popularity metadata.',
    joinKeys: ['fsq_id', 'chain_id', 'categories'],
    licenseNotes: 'Commercial API terms and attribution requirements apply.',
    caveats: ['Free tier is limited.', 'Not open redistribution data.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Foursquare, New York', lat: 40.7411, lng: -73.9897 },
    bbox: [-180, -85, 180, 85],
    status: 'commercial_candidate',
    scores: scores(4, 5, 5, 4, 5, 2, 4),
  },
  {
    id: 'placer-ai',
    name: 'Placer.ai API',
    provider: 'Placer.ai',
    category: 'cpg_retail',
    summary: 'Commercial foot traffic, trade areas, demographics, venue rankings, and visit trends.',
    coverage: 'us',
    gisMode: 'coordinates',
    output: 'time_series',
    endpointUrl: 'https://www.placer.ai/products/api',
    docsUrl: 'https://www.placer.ai/products/api',
    auth: 'commercial_contract',
    access: 'commercial',
    cadence: 'daily',
    spatialResolution: 'Venue, chain, trade area, DMA, and custom geography depending on contract.',
    joinKeys: ['venue_id', 'chain_id', 'trade_area'],
    licenseNotes: 'Commercial contract required.',
    caveats: ['Paid vendor source.', 'Privacy and redistribution terms must be reviewed.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Placer.ai, Los Altos', lat: 37.3852, lng: -122.1141 },
    bbox: [-125, 24, -66, 49],
    status: 'commercial_candidate',
    scores: scores(3, 5, 5, 4, 4, 1, 4),
  },
  {
    id: 'safegraph-places',
    name: 'SafeGraph Places and Geometry',
    provider: 'SafeGraph',
    category: 'cpg_retail',
    summary: 'Commercial POI, brand, address, polygon, and place attribution files.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'poi_points',
    endpointUrl: 'https://docs.safegraph.com/docs/delivery-file-structure',
    docsUrl: 'https://docs.safegraph.com/docs/places-schema',
    auth: 'commercial_contract',
    access: 'commercial',
    cadence: 'monthly',
    spatialResolution: 'POI point and polygon footprints.',
    joinKeys: ['placekey', 'safegraph_place_id', 'brand_id'],
    licenseNotes: 'Commercial license required.',
    caveats: ['Usually file delivery, not a live public API.', PROVIDER_POINT_CAVEAT],
    location: { label: 'SafeGraph, San Francisco', lat: 37.7749, lng: -122.4194 },
    bbox: [-180, -85, 180, 85],
    status: 'commercial_candidate',
    scores: scores(3, 5, 5, 2, 3, 1, 4),
  },
  {
    id: 'usda-fooddata-central',
    name: 'USDA FoodData Central API',
    provider: 'USDA Agricultural Research Service',
    category: 'cpg_retail',
    summary: 'Branded food, nutrition, ingredients, manufacturer, and product taxonomy metadata.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'enrichment_table',
    endpointUrl: 'https://api.nal.usda.gov/fdc/v1/foods/search',
    docsUrl: 'https://fdc.nal.usda.gov/api-guide/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Not GIS-native; joins to brands, manufacturers, stores, or recall geographies.',
    joinKeys: ['fdcId', 'gtinUpc', 'brandOwner'],
    licenseNotes: 'Public U.S. government data; API key via data.gov.',
    caveats: ['Product metadata only; geocoding requires external join.', PROVIDER_POINT_CAVEAT],
    location: { label: 'USDA ARS, Beltsville', lat: 39.0334, lng: -76.8836 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 2, 4, 5, 5, 4),
  },
  {
    id: 'usda-nass-quickstats',
    name: 'USDA NASS Quick Stats',
    provider: 'USDA National Agricultural Statistics Service',
    category: 'cpg_retail',
    summary: 'Agricultural production, acreage, livestock, prices, and commodity statistics by geography.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://quickstats.nass.usda.gov/api/api_GET/',
    docsUrl: 'https://quickstats.nass.usda.gov/api',
    auth: 'free_key',
    access: 'open',
    cadence: 'release_calendar',
    spatialResolution: 'State, county, watershed, and agricultural district depending on series.',
    joinKeys: ['state_fips_code', 'county_code', 'commodity_desc'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Release-calendar data, not live supply telemetry.', PROVIDER_POINT_CAVEAT],
    location: { label: 'USDA NASS, Washington DC', lat: 38.8867, lng: -77.0297 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 4, 2, 5, 5, 4),
  },
  {
    id: 'census-cbp-zbp',
    name: 'County and ZIP Business Patterns',
    provider: 'U.S. Census Bureau',
    category: 'cpg_retail',
    summary: 'Establishment counts, employment, and payroll by industry and geography.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://api.census.gov/data/timeseries/cbp',
    docsUrl: 'https://www.census.gov/data/developers/data-sets/cbp-zbp/cbp-api.html',
    auth: 'free_key',
    access: 'open',
    cadence: 'annual',
    spatialResolution: 'County, ZIP, metro, state, and national by NAICS.',
    joinKeys: ['GEOID', 'NAICS2017', 'YEAR'],
    licenseNotes: 'Public domain U.S. government data.',
    caveats: ['Annual benchmark, not live business opening data.', PROVIDER_POINT_CAVEAT],
    location: { label: 'U.S. Census Bureau, Suitland', lat: 38.8462, lng: -76.9274 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 4, 1, 5, 5, 5),
  },
  {
    id: 'lehd-lodes',
    name: 'LEHD LODES',
    provider: 'U.S. Census Bureau',
    category: 'cpg_retail',
    summary: 'Workplace, residence, and origin-destination employment flows for demand and daytime population.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://lehd.ces.census.gov/data/',
    docsUrl: 'https://lehd.ces.census.gov/data/lodes/LODES8/LODESTechDoc8.3.pdf',
    auth: 'none',
    access: 'open',
    cadence: 'annual',
    spatialResolution: 'Census block and workplace/residence flow geography.',
    joinKeys: ['w_geocode', 'h_geocode', 'S000'],
    licenseNotes: 'Public U.S. Census data product.',
    caveats: ['File based and annual.', PROVIDER_POINT_CAVEAT],
    location: { label: 'U.S. Census Bureau, Suitland', lat: 38.8462, lng: -76.9274 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(5, 5, 4, 1, 3, 5, 4),
  },
  {
    id: 'bls-public-data-api',
    name: 'BLS Public Data API',
    provider: 'U.S. Bureau of Labor Statistics',
    category: 'cpg_retail',
    summary: 'CPI, average prices, wages, employment, and labor market series by region.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'time_series',
    endpointUrl: 'https://api.bls.gov/publicAPI/v2/timeseries/data/',
    docsUrl: 'https://www.bls.gov/developers/',
    auth: 'free_key',
    access: 'open',
    cadence: 'monthly',
    spatialResolution: 'National, state, metro, and regional series depending on dataset.',
    joinKeys: ['series_id', 'area_code', 'industry_code'],
    licenseNotes: 'Public domain U.S. government data.',
    caveats: ['Registration improves rate limits.', PROVIDER_POINT_CAVEAT],
    location: { label: 'BLS, Washington DC', lat: 38.9089, lng: -77.0147 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 3, 3, 5, 5, 4),
  },
  {
    id: 'un-comtrade',
    name: 'UN Comtrade API',
    provider: 'United Nations Statistics Division',
    category: 'cpg_retail',
    summary: 'Global product and commodity trade flows by reporter, partner, and HS/SITC code.',
    coverage: 'global',
    gisMode: 'boundary_join',
    output: 'time_series',
    endpointUrl: 'https://comtradeapi.un.org/',
    docsUrl: 'https://comtradedeveloper.un.org/',
    auth: 'free_key',
    access: 'freemium',
    cadence: 'monthly',
    spatialResolution: 'Country-level trade flows.',
    joinKeys: ['reporterCode', 'partnerCode', 'cmdCode', 'period'],
    licenseNotes: 'UN terms and rate limits apply.',
    caveats: ['Country-level, not facility-level supply chain data.', PROVIDER_POINT_CAVEAT],
    location: { label: 'United Nations, New York', lat: 40.7492, lng: -73.968 },
    bbox: [-180, -85, 180, 85],
    status: 'candidate',
    scores: scores(5, 4, 3, 3, 4, 3, 3),
  },
  {
    id: 'openfda-drug',
    name: 'openFDA Drug APIs',
    provider: 'U.S. Food and Drug Administration',
    category: 'pharma_health',
    summary: 'Drug adverse events, labels, NDC, approvals, enforcement, and safety reports.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'enrichment_table',
    endpointUrl: 'https://api.fda.gov/drug/event.json',
    docsUrl: 'https://open.fda.gov/apis/drug/',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Not GIS-native; joins through manufacturer, facility, report, or recall geography.',
    joinKeys: ['spl_id', 'product_ndc', 'manufacturer_name', 'recall_number'],
    licenseNotes: 'Public FDA data with disclaimers.',
    caveats: ['Not a substitute for clinical or regulatory advice.', PROVIDER_POINT_CAVEAT],
    location: { label: 'FDA, Silver Spring', lat: 39.0347, lng: -76.9834 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 2, 4, 5, 5, 4),
  },
  {
    id: 'clinicaltrials-gov-api',
    name: 'ClinicalTrials.gov API v2',
    provider: 'National Library of Medicine',
    category: 'pharma_health',
    summary: 'Clinical trial records, sponsors, conditions, recruiting status, and facility locations.',
    coverage: 'global',
    gisMode: 'address_geocode',
    output: 'point_events',
    endpointUrl: 'https://clinicaltrials.gov/api/v2/studies',
    docsUrl: 'https://clinicaltrials.gov/data-about-studies/learn-about-api',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Facility address and city/state/country; geocoding needed for many studies.',
    joinKeys: ['nctId', 'orgStudyId', 'facility'],
    licenseNotes: 'Public domain U.S. government data with record-use disclaimers.',
    caveats: ['Facility addresses are not always complete.', PROVIDER_POINT_CAVEAT],
    location: { label: 'NLM, Bethesda', lat: 38.9955, lng: -77.0969 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(5, 5, 4, 4, 5, 5, 5),
  },
  {
    id: 'cdc-places',
    name: 'CDC PLACES',
    provider: 'Centers for Disease Control and Prevention',
    category: 'pharma_health',
    summary: 'Health outcomes, prevention, disability, and risk-factor estimates for local geographies.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://data.cdc.gov/resource/cwsq-ngmh.json',
    docsUrl: 'https://www.cdc.gov/places/',
    auth: 'none',
    access: 'open',
    cadence: 'annual',
    spatialResolution: 'County, place, tract, and ZCTA depending on release.',
    joinKeys: ['LocationID', 'MeasureId', 'Year'],
    licenseNotes: 'Public CDC data; methodology caveats required.',
    caveats: ['Modeled estimates, not real-time clinical surveillance.', PROVIDER_POINT_CAVEAT],
    location: { label: 'CDC, Atlanta', lat: 33.7995, lng: -84.328 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 5, 1, 4, 5, 5),
  },
  {
    id: 'cms-data-api',
    name: 'CMS Data API',
    provider: 'Centers for Medicare and Medicaid Services',
    category: 'pharma_health',
    summary: 'Provider, facility, payment, quality, utilization, and Medicare datasets.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'enrichment_table',
    endpointUrl: 'https://data.cms.gov/data-api/v1/dataset',
    docsUrl: 'https://data.cms.gov/api-docs',
    auth: 'none',
    access: 'open',
    cadence: 'monthly',
    spatialResolution: 'Provider and facility records with addresses and administrative geographies.',
    joinKeys: ['NPI', 'CCN', 'provider_id', 'zip'],
    licenseNotes: 'Public CMS data; privacy and methodology notes apply.',
    caveats: ['Dataset schemas vary across CMS products.', PROVIDER_POINT_CAVEAT],
    location: { label: 'CMS, Baltimore', lat: 39.2904, lng: -76.6122 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 3, 3, 4, 5, 4),
  },
  {
    id: 'nppes-npi-registry',
    name: 'NPPES NPI Registry API',
    provider: 'Centers for Medicare and Medicaid Services',
    category: 'pharma_health',
    summary: 'Provider identity, taxonomy, practice addresses, and organization lookup.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'poi_points',
    endpointUrl: 'https://npiregistry.cms.hhs.gov/api/',
    docsUrl: 'https://npiregistry.cms.hhs.gov/api-page',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Provider mailing and practice location addresses.',
    joinKeys: ['NPI', 'taxonomy', 'postal_code'],
    licenseNotes: 'Public registry data; operational use needs privacy review.',
    caveats: ['Addresses require geocoding before map rendering.', PROVIDER_POINT_CAVEAT],
    location: { label: 'CMS, Baltimore', lat: 39.2904, lng: -76.6122 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 4, 3, 4, 5, 4, 4),
  },
  {
    id: 'healthdata-gov',
    name: 'HealthData.gov',
    provider: 'U.S. Department of Health and Human Services',
    category: 'pharma_health',
    summary: 'HHS dataset catalog for health programs, facilities, public health, and APIs.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'enrichment_table',
    endpointUrl: 'https://healthdata.gov/api/3/action/package_search',
    docsUrl: 'https://healthdata.gov/',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Catalog metadata and dataset-specific spatial fields.',
    joinKeys: ['identifier', 'publisher', 'tags'],
    licenseNotes: 'Dataset-specific HHS terms.',
    caveats: ['Discovery catalog; downstream source validation still required.', PROVIDER_POINT_CAVEAT],
    location: { label: 'HHS, Washington DC', lat: 38.8867, lng: -77.0146 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(5, 4, 2, 3, 4, 4, 3),
  },
  {
    id: 'rxnorm-api',
    name: 'RxNorm API',
    provider: 'National Library of Medicine',
    category: 'pharma_health',
    summary: 'Normalized drug names, concepts, ingredients, brands, and identifiers.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'enrichment_table',
    endpointUrl: 'https://rxnav.nlm.nih.gov/REST/',
    docsUrl: 'https://lhncbc.nlm.nih.gov/RxNav/APIs/RxNormAPIs.html',
    auth: 'none',
    access: 'open',
    cadence: 'weekly',
    spatialResolution: 'Not GIS-native; enriches pharmacy, claims, trial, and FDA datasets.',
    joinKeys: ['rxcui', 'ndc', 'name'],
    licenseNotes: 'NLM terms apply.',
    caveats: ['Identifier enrichment only.', PROVIDER_POINT_CAVEAT],
    location: { label: 'NLM, Bethesda', lat: 38.9955, lng: -77.0969 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 4, 1, 3, 5, 5, 3),
  },
  {
    id: 'fda-enforcement-recalls',
    name: 'FDA Enforcement and Recalls',
    provider: 'U.S. Food and Drug Administration',
    category: 'pharma_health',
    summary: 'Drug, device, and food enforcement reports for recalls and regulated product disruptions.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'point_events',
    endpointUrl: 'https://api.fda.gov/drug/enforcement.json',
    docsUrl: 'https://open.fda.gov/apis/drug/enforcement/',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Firm city/state/country and product distribution pattern text.',
    joinKeys: ['recall_number', 'firm_name', 'product_type'],
    licenseNotes: 'Public FDA data with disclaimers.',
    caveats: ['Distribution patterns may be narrative and need parsing.', PROVIDER_POINT_CAVEAT],
    location: { label: 'FDA, Silver Spring', lat: 39.0347, lng: -76.9834 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 3, 4, 5, 5, 4),
  },
  {
    id: 'sec-edgar-apis',
    name: 'SEC EDGAR APIs',
    provider: 'U.S. Securities and Exchange Commission',
    category: 'finance_macro',
    summary: 'Company submissions, facts, frames, filings, and XBRL data for public issuers.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'time_series',
    endpointUrl: 'https://data.sec.gov/submissions/',
    docsUrl: 'https://www.sec.gov/search-filings/edgar-application-programming-interfaces',
    auth: 'none',
    access: 'open',
    cadence: 'real_time',
    spatialResolution: 'Company HQ addresses and filing metadata; facility geography requires extraction.',
    joinKeys: ['CIK', 'ticker', 'accessionNumber'],
    licenseNotes: 'Public SEC data; use fair-access user agent.',
    caveats: ['Use nightly bulk ZIPs for large-scale refresh.', PROVIDER_POINT_CAVEAT],
    location: { label: 'SEC, Washington DC', lat: 38.8977, lng: -77.0365 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 3, 5, 5, 5, 5),
  },
  {
    id: 'fred-api',
    name: 'FRED API',
    provider: 'Federal Reserve Bank of St. Louis',
    category: 'finance_macro',
    summary: 'Macro and regional economic time series for market, labor, inflation, and financial conditions.',
    coverage: 'global',
    gisMode: 'boundary_join',
    output: 'time_series',
    endpointUrl: 'https://api.stlouisfed.org/fred/series/observations',
    docsUrl: 'https://fred.stlouisfed.org/docs/api/fred/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Series-specific national, state, county, metro, and global geographies.',
    joinKeys: ['series_id', 'date'],
    licenseNotes: 'FRED terms and source attribution apply.',
    caveats: ['Series metadata must drive spatial interpretation.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Federal Reserve Bank of St. Louis', lat: 38.6305, lng: -90.1885 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(5, 5, 3, 4, 5, 4, 5),
  },
  {
    id: 'geofred-api',
    name: 'GeoFRED API',
    provider: 'Federal Reserve Bank of St. Louis',
    category: 'finance_macro',
    summary: 'Regional FRED data formatted for map-ready economic indicators.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://api.stlouisfed.org/geofred/regional/data',
    docsUrl: 'https://fred.stlouisfed.org/docs/api/geofred/regional_data.html',
    auth: 'free_key',
    access: 'open',
    cadence: 'release_calendar',
    spatialResolution: 'State, county, and metro depending on indicator.',
    joinKeys: ['region', 'series_id', 'date'],
    licenseNotes: 'FRED terms and source attribution apply.',
    caveats: ['Not all FRED series are available through GeoFRED.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Federal Reserve Bank of St. Louis', lat: 38.6305, lng: -90.1885 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 5, 3, 5, 4, 5),
  },
  {
    id: 'bea-api',
    name: 'BEA API',
    provider: 'U.S. Bureau of Economic Analysis',
    category: 'finance_macro',
    summary: 'GDP, personal income, industry, regional accounts, and trade statistics.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'time_series',
    endpointUrl: 'https://apps.bea.gov/api/data',
    docsUrl: 'https://www.bea.gov/API/signup/',
    auth: 'free_key',
    access: 'open',
    cadence: 'quarterly',
    spatialResolution: 'Nation, state, county, metro, and industry geographies depending on dataset.',
    joinKeys: ['GeoFIPS', 'LineCode', 'TimePeriod'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Release-calendar macro data, not live market telemetry.', PROVIDER_POINT_CAVEAT],
    location: { label: 'BEA, Suitland', lat: 38.8462, lng: -76.9274 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 4, 2, 5, 5, 4),
  },
  {
    id: 'cfpb-hmda',
    name: 'CFPB HMDA Platform',
    provider: 'Consumer Financial Protection Bureau',
    category: 'finance_macro',
    summary: 'Mortgage applications, originations, denials, lender activity, and housing credit geography.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://ffiec.cfpb.gov/v2/data-browser-api/view/csv',
    docsUrl: 'https://ffiec.cfpb.gov/documentation/publications/loan-level-datasets/lar-data-fields',
    auth: 'none',
    access: 'open',
    cadence: 'annual',
    spatialResolution: 'Census tract, county, metro, lender, and demographic dimensions.',
    joinKeys: ['census_tract', 'lei', 'activity_year'],
    licenseNotes: 'Public government data with privacy edits.',
    caveats: ['Sensitive market signal; avoid re-identification workflows.', PROVIDER_POINT_CAVEAT],
    location: { label: 'CFPB, Washington DC', lat: 38.8993, lng: -77.0422 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 5, 1, 4, 5, 5),
  },
  {
    id: 'usaspending-api',
    name: 'USAspending API',
    provider: 'U.S. Department of the Treasury',
    category: 'finance_macro',
    summary: 'Federal contracts, grants, loans, recipients, agencies, places of performance, and NAICS.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'point_events',
    endpointUrl: 'https://api.usaspending.gov/api/v2/search/spending_by_award/',
    docsUrl: 'https://api.usaspending.gov/docs/intro-tutorial',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Recipient location, place of performance, county, state, congressional district.',
    joinKeys: ['award_id', 'recipient_hash', 'naics_code', 'place_of_performance'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Locations can be award office, recipient, or performance geography.', PROVIDER_POINT_CAVEAT],
    location: { label: 'U.S. Treasury, Washington DC', lat: 38.8987, lng: -77.0348 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 4, 4, 5, 5, 5),
  },
  {
    id: 'eia-api',
    name: 'EIA API',
    provider: 'U.S. Energy Information Administration',
    category: 'finance_macro',
    summary: 'Energy production, consumption, prices, capacity, electricity, petroleum, and natural gas data.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'time_series',
    endpointUrl: 'https://api.eia.gov/v2/',
    docsUrl: 'https://www.eia.gov/opendata/documentation.php',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'National, PADD, state, balancing authority, and plant geographies.',
    joinKeys: ['series_id', 'stateid', 'plantCode', 'period'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Cadence varies widely by energy product.', PROVIDER_POINT_CAVEAT],
    location: { label: 'EIA, Washington DC', lat: 38.8853, lng: -77.025 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 4, 4, 5, 5, 4),
  },
  {
    id: 'openfigi-api',
    name: 'OpenFIGI API',
    provider: 'Bloomberg',
    category: 'finance_macro',
    summary: 'Security identifier mapping across FIGI, ticker, exchange, composite, and market sector.',
    coverage: 'global',
    gisMode: 'not_spatial_native',
    output: 'enrichment_table',
    endpointUrl: 'https://api.openfigi.com/v3/mapping',
    docsUrl: 'https://www.openfigi.com/api/documentation',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Not GIS-native; joins securities to issuers and markets.',
    joinKeys: ['figi', 'ticker', 'exchCode', 'micCode'],
    licenseNotes: 'OpenFIGI API terms and rate limits apply.',
    caveats: ['Identifier mapping only.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Bloomberg, New York', lat: 40.7614, lng: -73.9675 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(4, 4, 1, 4, 5, 4, 3),
  },
  {
    id: 'polygon-market-data',
    name: 'Polygon.io Market Data',
    provider: 'Polygon.io',
    category: 'finance_macro',
    summary: 'Real-time and historical equities, options, forex, indices, and crypto market data.',
    coverage: 'global',
    gisMode: 'not_spatial_native',
    output: 'time_series',
    endpointUrl: 'https://api.polygon.io/',
    docsUrl: 'https://polygon.io/docs',
    auth: 'account_key',
    access: 'commercial',
    cadence: 'real_time',
    spatialResolution: 'Not GIS-native; joins to exchange, issuer, HQ, or facility geography.',
    joinKeys: ['ticker', 'exchange', 'figi'],
    licenseNotes: 'Commercial market-data terms apply.',
    caveats: ['Paid tiers required for most real-time use.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Polygon.io, Atlanta', lat: 33.749, lng: -84.388 },
    bbox: [-180, -85, 180, 85],
    status: 'commercial_candidate',
    scores: scores(3, 4, 1, 5, 5, 1, 3),
  },
  {
    id: 'fhfa-house-price-index',
    name: 'FHFA House Price Index',
    provider: 'Federal Housing Finance Agency',
    category: 'finance_macro',
    summary: 'House price index data by state, metro, county, ZIP, and Census tract products.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://www.fhfa.gov/data/hpi',
    docsUrl: 'https://www.fhfa.gov/data/hpi',
    auth: 'none',
    access: 'open',
    cadence: 'quarterly',
    spatialResolution: 'State, metro, county, ZIP, and tract depending on release.',
    joinKeys: ['state', 'cbsa', 'county', 'tract', 'period'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Release-calendar index, not parcel-level transaction feed.', PROVIDER_POINT_CAVEAT],
    location: { label: 'FHFA, Washington DC', lat: 38.901, lng: -77.039 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(5, 4, 4, 2, 3, 5, 3),
  },
  {
    id: 'congress-gov-api',
    name: 'Congress.gov API',
    provider: 'Library of Congress',
    category: 'policy_regulation',
    summary: 'Bills, amendments, members, committees, nominations, treaties, and legislative actions.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'docket_feed',
    endpointUrl: 'https://api.congress.gov/v3/bill',
    docsUrl: 'https://api.congress.gov/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'National, member district, state, and committee metadata.',
    joinKeys: ['congress', 'billNumber', 'bioguideId', 'district'],
    licenseNotes: 'Public data; API key and attribution terms apply.',
    caveats: ['Policy text needs downstream topic/entity extraction for market impact.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Library of Congress, Washington DC', lat: 38.8887, lng: -77.0047 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 4, 3, 4, 5, 5, 4),
  },
  {
    id: 'federal-register-api',
    name: 'Federal Register API',
    provider: 'National Archives and Records Administration',
    category: 'policy_regulation',
    summary: 'Proposed rules, final rules, notices, presidential documents, agencies, and publication metadata.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'docket_feed',
    endpointUrl: 'https://www.federalregister.gov/api/v1/documents.json',
    docsUrl: 'https://www.federalregister.gov/developers/documentation/api/v1',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Not GIS-native; joins to agencies, affected regions, facilities, or industries.',
    joinKeys: ['document_number', 'agency_ids', 'publication_date', 'cfr_references'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Geography often inferred from text or agency jurisdiction.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Federal Register, Washington DC', lat: 38.8921, lng: -77.0241 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 2, 4, 5, 5, 4),
  },
  {
    id: 'regulations-gov-api',
    name: 'Regulations.gov API',
    provider: 'U.S. General Services Administration',
    category: 'policy_regulation',
    summary: 'Dockets, rulemaking documents, public comments, agencies, and regulatory proceedings.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'docket_feed',
    endpointUrl: 'https://api.regulations.gov/v4/documents',
    docsUrl: 'https://open.gsa.gov/api/regulationsgov/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Not GIS-native; geography from agencies, docket text, or commenter metadata where allowed.',
    joinKeys: ['docketId', 'documentId', 'agencyId'],
    licenseNotes: 'Public data with API terms and comment-data privacy limits.',
    caveats: ['Requires API key.', 'Do not expose personal data from comments.', PROVIDER_POINT_CAVEAT],
    location: { label: 'GSA, Washington DC', lat: 38.8836, lng: -77.0199 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 2, 4, 5, 4, 4),
  },
  {
    id: 'fec-api',
    name: 'FEC API',
    provider: 'Federal Election Commission',
    category: 'policy_regulation',
    summary: 'Candidates, committees, filings, receipts, disbursements, and independent expenditures.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'point_events',
    endpointUrl: 'https://api.open.fec.gov/v1/',
    docsUrl: 'https://api.open.fec.gov/developers/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Committee, candidate, contributor, state, district, and filing metadata.',
    joinKeys: ['committee_id', 'candidate_id', 'state', 'district'],
    licenseNotes: 'Public campaign-finance data; legal restrictions apply to solicitation use.',
    caveats: ['Do not use contributor data for prohibited solicitation.', PROVIDER_POINT_CAVEAT],
    location: { label: 'FEC, Washington DC', lat: 38.9048, lng: -77.0312 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 4, 3, 4, 5, 3, 3),
  },
  {
    id: 'openstates-api',
    name: 'Open States API',
    provider: 'Open States',
    category: 'policy_regulation',
    summary: 'State legislation, legislators, committees, events, and jurisdiction metadata.',
    coverage: 'state_local',
    gisMode: 'boundary_join',
    output: 'docket_feed',
    endpointUrl: 'https://v3.openstates.org/',
    docsUrl: 'https://docs.openstates.org/',
    auth: 'account_key',
    access: 'freemium',
    cadence: 'daily',
    spatialResolution: 'State, chamber, district, and jurisdiction metadata.',
    joinKeys: ['jurisdiction', 'identifier', 'person_id', 'district'],
    licenseNotes: 'Open States API terms and attribution apply.',
    caveats: ['API access terms and quotas apply.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Open States, Washington DC', lat: 38.9072, lng: -77.0369 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(4, 4, 3, 4, 4, 3, 3),
  },
  {
    id: 'sam-gov-opportunities',
    name: 'SAM.gov Opportunities API',
    provider: 'U.S. General Services Administration',
    category: 'policy_regulation',
    summary: 'Federal contract opportunities, notices, agencies, NAICS, PSC, and place-of-performance hints.',
    coverage: 'us',
    gisMode: 'address_geocode',
    output: 'point_events',
    endpointUrl: 'https://api.sam.gov/opportunities/v2/search',
    docsUrl: 'https://open.gsa.gov/api/get-opportunities-public-api/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Place of performance and office addresses where provided.',
    joinKeys: ['noticeId', 'solicitationNumber', 'naicsCode', 'placeOfPerformance'],
    licenseNotes: 'Public government procurement data with API key terms.',
    caveats: ['Requires API key.', 'Locations may be contracting office rather than worksite.', PROVIDER_POINT_CAVEAT],
    location: { label: 'GSA, Washington DC', lat: 38.8836, lng: -77.0199 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(5, 5, 3, 4, 4, 5, 4),
  },
  {
    id: 'govinfo-api',
    name: 'GovInfo API',
    provider: 'U.S. Government Publishing Office',
    category: 'policy_regulation',
    summary: 'Federal legislative, regulatory, judicial, and executive publications and packages.',
    coverage: 'us',
    gisMode: 'not_spatial_native',
    output: 'docket_feed',
    endpointUrl: 'https://api.govinfo.gov/',
    docsUrl: 'https://api.govinfo.gov/docs/',
    auth: 'free_key',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Document metadata; geography inferred from content or related agencies.',
    joinKeys: ['packageId', 'collectionCode', 'dateIssued'],
    licenseNotes: 'Public U.S. government publication data with API key terms.',
    caveats: ['Document API, not a GIS source.', PROVIDER_POINT_CAVEAT],
    location: { label: 'GPO, Washington DC', lat: 38.8951, lng: -77.0132 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(5, 3, 1, 4, 4, 5, 2),
  },
  {
    id: 'state-local-open-data-portals',
    name: 'State and Local Open Data Portals',
    provider: 'State, county, and city publishers',
    category: 'policy_regulation',
    summary: 'Permits, inspections, zoning, taxes, agenda items, contracts, health, and business license datasets.',
    coverage: 'state_local',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://dev.socrata.com/docs/endpoints',
    docsUrl: 'https://dev.socrata.com/docs/endpoints',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'Dataset-specific addresses, points, polygons, and local boundaries.',
    joinKeys: ['dataset_id', 'license_number', 'parcel_id', 'permit_id'],
    licenseNotes: 'Publisher-specific local open data terms.',
    caveats: ['Requires per-portal dataset selection and schema normalization.', PROVIDER_POINT_CAVEAT],
    location: { label: 'Representative local portal, New York City', lat: 40.7128, lng: -74.006 },
    bbox: [-125, 24, -66, 49],
    status: 'candidate',
    scores: scores(4, 5, 4, 4, 4, 3, 4),
  },
  {
    id: 'gdelt-api',
    name: 'GDELT APIs',
    provider: 'GDELT Project',
    category: 'live_risk',
    summary: 'Global news, events, themes, entities, tone, sources, and geography-aware media monitoring.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://api.gdeltproject.org/api/v2/geo/geo',
    docsUrl: 'https://blog.gdeltproject.org/gdelt-geo-2-0-api-debuts/',
    auth: 'none',
    access: 'open',
    cadence: 'minutes',
    spatialResolution: 'Article and event locations inferred from media content.',
    joinKeys: ['url', 'sourceCountry', 'theme', 'location'],
    licenseNotes: 'GDELT terms and source attribution apply.',
    caveats: ['Geocoding and event extraction can be noisy.', PROVIDER_POINT_CAVEAT],
    location: { label: 'GDELT Project, Mountain View', lat: 37.3861, lng: -122.0839 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(4, 5, 4, 5, 4, 4, 5),
  },
  {
    id: 'noaa-nws-api',
    name: 'NOAA National Weather Service API',
    provider: 'National Weather Service',
    category: 'live_risk',
    summary: 'Weather alerts, observations, forecasts, grids, zones, and CAP-compatible public warnings.',
    coverage: 'us',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://api.weather.gov/alerts/active',
    docsUrl: 'https://www.weather.gov/documentation/services-web-api',
    auth: 'none',
    access: 'open',
    cadence: 'real_time',
    spatialResolution: 'Alert polygons, zones, points, offices, and forecast grids.',
    joinKeys: ['id', 'areaDesc', 'geocode', 'event'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Reasonable rate limits are enforced but not fully published.', PROVIDER_POINT_CAVEAT],
    location: { label: 'NWS, Silver Spring', lat: 39.0347, lng: -76.9834 },
    bbox: [-179.15, 17.67, -65.0, 71.55],
    status: 'ready',
    scores: scores(5, 5, 5, 5, 5, 5, 5),
  },
  {
    id: 'usgs-earthquake-feeds',
    name: 'USGS Earthquake GeoJSON Feeds',
    provider: 'U.S. Geological Survey',
    category: 'live_risk',
    summary: 'Minute-updated global earthquake event feeds with magnitude, depth, time, and geometry.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson',
    docsUrl: 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php',
    auth: 'none',
    access: 'open',
    cadence: 'real_time',
    spatialResolution: 'Event epicenter point with depth.',
    joinKeys: ['id', 'time', 'place', 'mag'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Event parameters can be revised after initial publication.', PROVIDER_POINT_CAVEAT],
    location: { label: 'USGS, Reston', lat: 38.9474, lng: -77.3678 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(5, 4, 5, 5, 5, 5, 5),
  },
  {
    id: 'nasa-firms',
    name: 'NASA FIRMS API',
    provider: 'NASA LANCE FIRMS',
    category: 'live_risk',
    summary: 'Near-real-time active fire and hotspot detections from MODIS and VIIRS sensors.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://firms.modaps.eosdis.nasa.gov/api/',
    docsUrl: 'https://firms.modaps.eosdis.nasa.gov/api/',
    auth: 'free_key',
    access: 'open',
    cadence: 'real_time',
    spatialResolution: 'Satellite fire detections with confidence and acquisition time.',
    joinKeys: ['latitude', 'longitude', 'acq_date', 'instrument'],
    licenseNotes: 'NASA data policy and attribution apply.',
    caveats: ['Requires free MAP_KEY for API access.', 'Hotspots are detections, not incident boundaries.', PROVIDER_POINT_CAVEAT],
    location: { label: 'NASA Goddard, Greenbelt', lat: 38.9958, lng: -76.8524 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(5, 5, 5, 5, 5, 5, 5),
  },
  {
    id: 'openaq-api',
    name: 'OpenAQ API v3',
    provider: 'OpenAQ',
    category: 'live_risk',
    summary: 'Global air quality measurements, locations, sensors, parameters, and latest observations.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://api.openaq.org/v3/latest',
    docsUrl: 'https://docs.openaq.org/',
    auth: 'free_key',
    access: 'open',
    cadence: 'minutes',
    spatialResolution: 'Monitoring station point observations.',
    joinKeys: ['location_id', 'parameter', 'datetime', 'coordinates'],
    licenseNotes: 'OpenAQ terms and source attribution apply.',
    caveats: ['Station coverage varies by country and network.', PROVIDER_POINT_CAVEAT],
    location: { label: 'OpenAQ, Washington DC', lat: 38.9072, lng: -77.0369 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(4, 4, 5, 5, 4, 4, 4),
  },
  {
    id: 'airnow-api',
    name: 'AirNow API',
    provider: 'U.S. Environmental Protection Agency',
    category: 'live_risk',
    summary: 'Current and forecast air quality observations for U.S. monitoring locations.',
    coverage: 'us',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://www.airnowapi.org/aq/observation/latLong/current/',
    docsUrl: 'https://docs.airnowapi.org/',
    auth: 'free_key',
    access: 'open',
    cadence: 'minutes',
    spatialResolution: 'Station or area observations depending on query.',
    joinKeys: ['AQI', 'ParameterName', 'ReportingArea', 'Latitude', 'Longitude'],
    licenseNotes: 'EPA AirNow API terms apply.',
    caveats: ['Observations are preliminary and not regulatory-grade.', PROVIDER_POINT_CAVEAT],
    location: { label: 'EPA, Washington DC', lat: 38.8939, lng: -77.0314 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 4, 4, 5, 4, 4, 4),
  },
  {
    id: 'reliefweb-api',
    name: 'ReliefWeb API',
    provider: 'UN OCHA',
    category: 'live_risk',
    summary: 'Humanitarian reports, disasters, maps, jobs, countries, organizations, and source metadata.',
    coverage: 'global',
    gisMode: 'boundary_join',
    output: 'docket_feed',
    endpointUrl: 'https://api.reliefweb.int/v1/reports',
    docsUrl: 'https://apidoc.reliefweb.int/',
    auth: 'none',
    access: 'open',
    cadence: 'minutes',
    spatialResolution: 'Country, disaster, and report metadata; many records need geocoding from text.',
    joinKeys: ['id', 'country.iso3', 'disaster.id', 'source.shortname'],
    licenseNotes: 'ReliefWeb API terms and source attribution apply.',
    caveats: ['Report geography can be broad.', PROVIDER_POINT_CAVEAT],
    location: { label: 'UN OCHA, Geneva', lat: 46.2044, lng: 6.1432 },
    bbox: [-180, -85, 180, 85],
    status: 'ready',
    scores: scores(5, 4, 3, 4, 5, 4, 4),
  },
  {
    id: 'acled-api',
    name: 'ACLED API',
    provider: 'Armed Conflict Location and Event Data',
    category: 'live_risk',
    summary: 'Political violence, protest, conflict, and disorder events with coordinates and actors.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://api.acleddata.com/acled/read',
    docsUrl: 'https://acleddata.com/acled-api-documentation',
    auth: 'account_key',
    access: 'restricted',
    cadence: 'daily',
    spatialResolution: 'Event coordinates with administrative hierarchy.',
    joinKeys: ['event_id_cnty', 'event_date', 'actor1', 'admin1'],
    licenseNotes: 'Access and redistribution governed by ACLED terms.',
    caveats: ['Authentication and usage terms required.', PROVIDER_POINT_CAVEAT],
    location: { label: 'ACLED, Madison', lat: 43.0747, lng: -89.3844 },
    bbox: [-180, -85, 180, 85],
    status: 'restricted_candidate',
    scores: scores(5, 4, 5, 4, 4, 2, 4),
  },
  {
    id: 'openfema-api',
    name: 'OpenFEMA API',
    provider: 'Federal Emergency Management Agency',
    category: 'live_risk',
    summary: 'Disaster declarations, public assistance, hazard mitigation, grants, and FEMA program datasets.',
    coverage: 'us',
    gisMode: 'boundary_join',
    output: 'choropleth',
    endpointUrl: 'https://www.fema.gov/openfema-data-hub',
    docsUrl: 'https://www.fema.gov/about/openfema/api',
    auth: 'none',
    access: 'open',
    cadence: 'daily',
    spatialResolution: 'State, county, ZIP, disaster area, and program-specific geography.',
    joinKeys: ['disasterNumber', 'state', 'designatedArea', 'fipsStateCode', 'fipsCountyCode'],
    licenseNotes: 'Public U.S. government data.',
    caveats: ['Versioned endpoints and pagination require careful handling.', PROVIDER_POINT_CAVEAT],
    location: { label: 'FEMA, Washington DC', lat: 38.8807, lng: -77.0365 },
    bbox: [-125, 24, -66, 49],
    status: 'ready',
    scores: scores(5, 5, 4, 4, 4, 5, 4),
  },
  {
    id: 'gdacs-api',
    name: 'GDACS Feeds',
    provider: 'Global Disaster Alert and Coordination System',
    category: 'live_risk',
    summary: 'Global disaster alerts for earthquakes, tropical cyclones, floods, volcanoes, droughts, and tsunamis.',
    coverage: 'global',
    gisMode: 'coordinates',
    output: 'point_events',
    endpointUrl: 'https://www.gdacs.org/xml/rss.xml',
    docsUrl: 'https://www.gdacs.org/About/overview.aspx',
    auth: 'none',
    access: 'open',
    cadence: 'minutes',
    spatialResolution: 'Event point, alert area, or affected country depending on hazard.',
    joinKeys: ['eventid', 'eventtype', 'alertlevel', 'country'],
    licenseNotes: 'GDACS terms and source attribution apply.',
    caveats: ['Feeds are alert products, not full loss models.', PROVIDER_POINT_CAVEAT],
    location: { label: 'JRC, Ispra', lat: 45.8081, lng: 8.6262 },
    bbox: [-180, -85, 180, 85],
    status: 'candidate',
    scores: scores(5, 4, 4, 4, 3, 4, 3),
  },
] as const satisfies readonly MarketResearchSource[];

export const MARKET_SOURCE_CATALOG_UPDATED_AT = '2026-05-24T00:00:00.000Z';

export const marketSourceFilters: MarketSourceFilters = {
  categories: MARKET_SOURCE_CATEGORIES,
  access: MARKET_SOURCE_ACCESS,
  auth: MARKET_SOURCE_AUTH,
  cadences: MARKET_SOURCE_CADENCES,
  coverage: MARKET_SOURCE_COVERAGE,
  outputs: MARKET_SOURCE_OUTPUTS,
  statuses: MARKET_SOURCE_STATUSES,
};

export const marketSourceCountsByCategory = marketResearchSources.reduce<Record<MarketSourceCategory, number>>((counts, source) => {
  counts[source.category] += 1;
  return counts;
}, {
  backbone: 0,
  cpg_retail: 0,
  pharma_health: 0,
  finance_macro: 0,
  policy_regulation: 0,
  live_risk: 0,
});
